[package]
name = "gbdaa"
version = "0.1.0"
authors = ["Boris Resnick <boris@resnick.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timer = "0.2.0"
chrono = "0.4"
